### ISSUE TITLE
How about to rename `neuro acl` -> `neuro perm`?

### ISSUE THREAD

**Issue by atemate** [neuro-inc/apolo-cli#802]
Perhaps, the term ACL is too engineering, and for an average data scientist this abbreviation may be unclear.

So this issue proposes one of the following options:
1. Rename `neuro acl grant/revoke/list` to `neuro perm[ission] grant/revoke/list`
2. Add explanation of what do the letters `ACL` mean in the help message

**Comment by ayushkovskiy** [comment]
@asvetlov My idea, which was not welcomed by Adnreas from the marketing point of view, was the opposite: `neuro` -> `neu`, and I still think it's a good idea.
`
